#!/usr/bin/env bash
cat <<EOF
// Do not edit this file, it is auto-generated
const unsigned char build_info[] =
	"* (C)2026 LGB (Gábor Lénárt) `git config --get remote.origin.url`\r\n"
	"* Compiled by `whoami`@`uname -n` at `date`\r\n"
	"* Git `git branch --show-current` `git log | awk '{ print $2 ; exit }'`\r\n"
;
EOF
